### ISSUE TITLE
Saga Worker Task Executed Twice on Full Browser Refresh

### ISSUE THREAD

**Issue by sagarpatel8384** [redux-saga/redux-saga#1378] opened 2018-03-28 04:01 UTC
I'm new to redux-saga and trying to replace redux-thunk in my React application. For some strange reason, my async task (worker) is being executed twice (but only when there's an AJAX request inside -- doesn't happen when there is a normal side effect e.g., console.log). 

As you can see from below, I call my getChildData only once in componentDidMount. However, my getChildDataAsync generator function executes twice (unless I comment out getChildData (which is an async request returning a promise). The request works and I see my response data, but then another request is fired off.

At first I thought this may have to do with location change but this happens on first visit to the website/hard refresh. 

Here is how I have saga set up:

**saga.js**

    import axios from 'axios';
    import { call, put, take, cancel, takeLatest } from 'redux-saga/effects';
    import { push, LOCATION_CHANGE } from 'react-router-redux';
    import {
      CHILD_DATA_LOADING,
      CHILD_DATA_SUCCESS,
      CHILD_DATA_ERROR,
    } from 'src/redux/actions/actionTypes';
    import { getChildData } from 'src/api/search';
    
    // Worker Saga - API Request
    export function* getChildDataAsync(action) {
      const { id } = action;
      const params = { id, storageKeys, dataCategory, from };
    
      try {
        const response = yield call(getChildData, params);
        yield put({
          type: CHILD_DATA_SUCCESS,
          childData: response.data,
        });
      } catch (error) {
        yield put({
          type: CHILD_DATA_ERROR,
          childDataError: true,
          error,
        });
      }
    }
    
    // Watcher Saga
    export function* watchGetChildData() {
      const childWatcher = yield takeLatest(CHILD_DATA_SUCCESS, getChildDataAsync);
    }
    
    // Root Saga - Generator Function
    export default function* rootSaga() {
      yield [
        // Combine all watcher sagas
        watchGetChildData(),
      ];
    }

**store.js**

    // @flow
    import { createStore, applyMiddleware } from 'redux';
    import { routerMiddleware } from 'react-router-redux';
    import createHistory from 'history/createHashHistory';
    import rootReducer from 'src/redux/reducers/index';
    import { createLogger } from 'redux-logger';
    import createSagaMiddleware from 'redux-saga';
    import rootSaga from 'src/redux/sagas/sagas';
    import thunk from 'redux-thunk';
    
    // React Router Redux
    export const history = createHistory();
    
    // Redux Saga
    const sagasMiddleware = createSagaMiddleware();
    
    // Add Redux Logging Only to DEV/TST Environments
    const middleware = applyMiddleware(thunk, sagasMiddleware, routerMiddleware(history));
    
    // Create store
    const store = createStore(rootReducer, middleware);
    
    // Run Redux-Saga Watchers
    sagasMiddleware.run(rootSaga);
    
    export default store;

**childDataCreator.js**

    // @flow
    import {
      CHILD_DATA_SUCCESS,
      CHILD_DATA_ERROR,
    } from 'src/redux/actions/actionTypes';
   
    
    // Description: Async Request to Get Child Data for Vendors/Sets
    export function getChildData(
      id: string,
    ) {
      return { type: CHILD_DATA_SUCCESS, id };
    }

**React Component**

    class DataView extends Component<Props> {
      componentDidMount() {
          const _id = '12345';
          this.props.getChildData(_id);
        }
      }
    
      rest of class....

**Comment by Andarist** [comment] 2018-03-28 22:28
Could u share a reproduced issue on something like codesandbox.io ? Are u sure that the first request of those in question is not an OPTIONS preflight? Does ur `CHILD_DATA_SUCCESS` get dispatched twice?

**Comment by liyun074** [comment] 2018-05-24 07:45
@sagarpatel8384   I also encountered the same problem, how do you solve it?

**Comment by Andarist** [comment] 2018-06-03 19:06
Closing because original author did not respond in a very long time. If you post a runnable example of the described behaviour I might take a look, but if not I won't be able to help.

**Closed by Andarist** 2018-06-03 19:06 UTC

**Comment by anuragb26** [comment] 2019-01-18 11:32
Facing the same issue
