### ISSUE TITLE
Intermittent freezing in firefox

### ISSUE THREAD

**Issue by ericp96** [redux-saga/redux-saga#2158] opened 2021-01-25 17:30 UTC
#### Description of the bug/issue
Sagas intermittently fail in firefox.  On load, no sagas seem to respond in spite of them being registered.  There's no rhyme or reason as to exactly why, however downgrading per [this comment](https://github.com/redux-saga/redux-saga/issues/1896#issuecomment-520455848) seems to resolve it. 

Using this top level saga pattern

```js
function* rootSaga () {
  const sagas = [
    saga1,
    saga2,
    saga3,
  ];

  yield all(sagas.map(saga =>
    spawn(function* () {
      while (true) {
        try {
          yield call(saga)
          break
        } catch (e) {
          console.log(e)
        }
      }
    }))
  );
}

...
// with the standard boilerplate:
const middleware = compose(applyMiddleware(sagaMiddleware, session), devTools);

const store = createStore(rootReducer, state, middleware);
sagaMiddleware.run(rootSaga)
```

And have modified all of our sagas to log when they have been entered into like this:
```js
function* sagaFn() {
  console.log('Called sagaFn');
  // ... more logic to follow
  console.log('Leaving sagaFn');
}

function* saga() {
  yield takeLeading('ACTION', sagaFn);
}
```

We then have react components that will do stuff like this:

```js
const Component = () => {
  const dispatch = useDispatch();

  useEffect(() => {
    dispatch({ type: 'ACTION' });
  }, []);
};
```
Expected: logs every time the component mounts
Actual: sometimes logs never display.  We can take react out of the issue in fact because dispatching via redux dev tools after the fact still doesn't trigger the saga.  None of my sagas ever write a log.  This seems to only impact firefox.

My hypothesis on this is that the issue can be attributed to my atypical setup.  I have a third party vendor that we have given a nested redux store along with redux saga.  The failures seem to happen on the nested instance only.  However, I don't have strong evidence one way or the other.

I expect this issue will likely go nowhere because the sporadic nature of the issue is making it hard to come up with an example that can be easily reproduced, but I figured it would be worth submitting an issue on in case if someone else experiences the same and can provide further documentation.

#### Steps to reproduce the bug/issue
In the sandbox that I've created below:
1. Use firefox
2. Refresh the page until the text "Todo from redux saga" no longer appears
**NOTE: The issue is intermittent and may not reproduce in this circumstance, I've extracted as much code as I could from the issue but I can't guarantee the issue is happening here.**

#### Example
https://stackblitz.com/edit/react-s4hp1t?file=src/createOuterStore.js

### Actual results
Redux saga works most of the time, but sporadically will do nothing in some versions of firefox about 30% of the time in our setup

### The Expected results
Redux saga should trigger on every page load

### Environment information
redux-saga 1.1.3
babel: 7.3.3
webpack: 4.41.5

Windows Version: Windows 10 Enterprise
Firefox Version: 1909
OS build 18363.1256

**Comment by boonep** [comment] 2021-03-22 17:46
Same exact issue.  Experiencing random failures of sagas on firefox only.

redux-saga: 1.1.3

macOS Big Sir 11.2.3
Firefox 86.0.1 (64-bit)

**Comment by boonep** [comment] 2021-03-22 18:54
Our issue was actually caused by a conflict with a third-party js script. Specifically userSnap & their "destroy()" method.  I'm not sure of the internal implementation of this method on their side, but this was causing sagas to fail intermittently when called.  https://help.usersnap.com/docs/api-for-usersnap-project#destroy-the-api

Removing the usage of this method solved all of our issues.  

P.S. the intermittency was occurring across firefox & safari with Safari failing way more consistently.  Chrome seemed to work fine always.

**Comment by neurosnap** [comment] 2022-02-27 02:37
Sorry it’s been awhile since any activity, but do you still see any issues with firefox freezing?  I’ve been using redux-saga in production environments for years and haven’t encountered this issue.

I’m going to close this issue for now.  If firefox is still freezing I can reopen and try to help debug.  Thanks!

**Closed by neurosnap** 2022-02-27 02:37 UTC

**Comment by ericp96** [comment] 2022-02-27 03:37
No worries, I get it.  This library is generally very stable (this issue aside :)).  I never did figure it out.  As the author before you commented, it was a conflict for them between redux-saga and a third party library, I never had the time to invest in it to figure it out.  I just rolled back the library and took a different approach.  Sorry! I wish I could be more helpful on that one!
