### ISSUE TITLE
`all` not properly exported from redux-saga/effects 

### ISSUE THREAD

**Issue by jforaker** [redux-saga/redux-saga#1261] opened 2017-11-13 16:54 UTC
`0.16.0`

`all` cannot be imported because it is not found in `redux-saga/effects`

Ran a clean install on 0.16.0 and seeing the issue

As you can see in the screenshot `all` is not part of the webpack imported module.

![image](https://user-images.githubusercontent.com/2042031/32737789-0265db6a-c869-11e7-986c-7e67e59f081d.png)

**Comment by Andarist** [comment] 2017-11-13 18:06
Are you sure that you do not have multiple versions of the `redux-saga` installed? I have no problem with using `all` and [it's exported](https://github.com/redux-saga/redux-saga/blob/658372c9cfbaf7435600e1372739e9c78c32b202/src/effects.js#L6) just fine

**Comment by jforaker** [comment] 2017-11-13 20:13
Interesting - when I build my app in production mode it seems to work. I wonder if there is anything affected by the `NODE_ENV=development` flag?  I am using https://github.com/react-boilerplate/react-boilerplate

**Comment by Andarist** [comment] 2017-11-13 23:19
>  I wonder if there is anything affected by the NODE_ENV=development flag

Not when it comes to exports.

**Comment by Peterabsolon** [comment] 2017-11-14 10:00
@jforaker As a workaround, you can try to import the effects from 'redux-saga/es/effects' instead. Worked for me.

**Comment by Andarist** [comment] 2017-11-14 10:46
I would advise to get to the bottom of it instead of using a temporary workaround. Just put a console.log in both `node_modules/redux-saga/es/effects` and `node_modules/redux-saga/lib/effects` to see if any of them gets imported by your bundler.

**Comment by jforaker** [comment] 2017-11-15 02:00
thanks @Peterabsolon that actually worked for the most part. However, now I'm experiencing an unexpected response. Using it according to the [the docs](https://redux-saga.js.org/docs/api/#alleffects-parallel-effects), I get a strange return value, as if it hasnt "resolved" for lack of a better term

```javascript
    const foo = yield all([
      call(request, getStoryUrl(id), includeCreds),
      call(request, `${getStoryUrl(id)}/history?page_size=5`, includeCreds)
    ]);
    console.log('foo', foo);
```

Result:
![image](https://user-images.githubusercontent.com/2042031/32814806-8bc5fa28-c97e-11e7-8447-4599b5a0c7d7.png)


And cannot spread the result like the docs because that object is not iterable. 

Any thoughts?  Or should I chalk it up to a corrupt install or node_module setup and move on? Either way is fine for me.

**Comment by Andarist** [comment] 2017-11-15 10:00
For me it looks like your `redux-saga` got imported from the other version laying in your `node_modules` or something and that it is a version that do not understand `all` yet - values that are not recognized by the saga's runtime are returned to the caller "as is". 

Im not sure how were you possible to import `all` from `redux-saga/es/effects` in such case, but possibly you import `all` and `createSagaMiddleware` (default export) from other directories and your's bundler resolution algorithm is going nuts somehow.

You can try:
- `console.log(all.toString())` + `console.log(createSagaMiddleware.toString())` and try to locate those modules on your disk
- removing manually found module and checking if you still can import it in your project (if yes then it would mean you have the module somewhere else on the disk too)

**Comment by jforaker** [comment] 2017-11-17 19:26
I've tried everything from wiping out node_modules and re-installing to trying the `es/effects` import. It must be something with my local environment, unrelated to the library. Thanks for the help, and feel free to close this issue (or let me know if I need to).

**Comment by Andarist** [comment] 2017-11-17 20:07
If you could share some repository with this thing reproduced, I could try to help you figuring this out. Feel free to response back here at any time - even though I'm closing this issue now.

**Closed by Andarist** 2017-11-17 20:07 UTC

**Comment by jforaker** [comment] 2017-11-17 21:13
I would really love to... but it is private/for work.  Our project was initialized with https://github.com/react-boilerplate/react-boilerplate and we haven't changed any webpack configs (though it might be a slightly older version)
