### ISSUE TITLE
uncaught error make the action never be taken anymore?

### ISSUE THREAD

**Issue by paranoidjk** [redux-saga/redux-saga#814] opened 2017-02-08 09:52 UTC
hello,

I noticed that if **a effects throw a error which not be catched**,  then dispatch the same action will never call the effect anymore.

I want to konw if i am understand correctly,  and why this?

**Comment by Andarist** [comment] 2017-02-08 11:39
That's probably because your sagas crashed. You need to implement proper error handling. `redux-saga` is kinda the interpreter of what you yield and handle it on its terms - within the same call stack, so if there is an error somewhere it cannot recover for you to the consistent point. You need to write some `try/catch` occasionally. It depends what error was thrown though.

Could you provide a code example of the described behaviour? The issue is desribed really vaguely now.

**Comment by Andarist** [comment] 2017-02-15 21:20
Going to close this, if you have any further questions - please just ask :)

**Closed by Andarist** 2017-02-15 21:20 UTC
Labels: question
