### ISSUE TITLE
Put action is bubbling errors

### ISSUE THREAD

**Issue by Gedzis** [redux-saga/redux-saga#1844] opened 2019-05-03 14:07 UTC
#### Description of the bug/issue
In https://redux-saga.js.org/docs/api/#putaction is described, that `This effect is non-blocking and any errors that are thrown downstream (e.g. in a reducer) will not bubble back into the saga.`. In my provided example, if there is an error in reducer it still bubbles and is catched by saga.

#### Steps to reproduce the bug/issue

1. Execute action in saga
2. Catch action in reducer and throw an exception
...

#### Example
https://codesandbox.io/s/oo3mjjwj1q

### The Expected results
As I understand, in this case, error should not bubble up to saga.

### Environment information
redux-saga version  - 1.0.2

**Comment by kitfit-dave** [comment] 2019-05-17 02:02
Hi. I can confirm that I am seeing the same issue. I've verified that if the action that is put triggers a reducer that throws, OR even if that reducer triggers a render that throws (!!!) - then the exception will be bubbled up right at the `yield put`...
I am -pretty sure- that this was not the case some time ago... that may not be true though.

react-saga 1.0.2
react-redux 5.1.1
react 16.8.6

I noticed this when running code much like any example, and seeing both the success action and the fail action getting put, e.g:

```
function* fetchProducts() {
  try {
    const products = yield call(Api.fetch, '/products')
    yield put({ type: 'PRODUCTS_RECEIVED', products })
  }
  catch(error) {
    yield put({ type: 'PRODUCTS_REQUEST_FAILED', error })
  }
}
```

where, when the PRODUCTS_RECEIVED reducer throws, you get PRODUCTS_REQUEST_FAILED also.

**Comment by trannamquan** [comment] 2019-09-09 11:08
I faced the same issue.

**Comment by Andarist** [comment] 2019-09-09 13:35
This is expected change described in the release notes - https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0
> errors thrown during put execution are no longer caught and swallowed, you need to catch them manually

**Comment by kitfit-dave** [comment] 2019-09-09 22:21
I guess that https://redux-saga.js.org/docs/api/ should be updated to reflect that. I guess this change is going to make it interesting when something downstream like a render exception needs to be handled in the saga.

**Comment by Andarist** [comment] 2019-09-10 07:00
Yeah, docs have been fixed in https://github.com/redux-saga/redux-saga/pull/1922 - just haven't time to do a fresh release. Going to take care of that soon.

> I guess this change is going to make it interesting when something downstream like a render exception needs to be handled in the saga.

Well, such errors shouldn't really be handled by the saga - they should be handled closer to the originating call site (most likely render/reducer). They will bubble up though and have the potential to kill your saga if the error stays unhandled because swallowing errors completely is a bad thing to do. This is very definition of "unhandled" exception - and in such situation, we can't assume that a system/app is stable, continuing might lead to unpredictable results so it's better to shut down the system.

**Comment by kitfit-dave** [comment] 2019-09-10 09:29
I agree completely. I guess my comment should have been “when an unhandled render exception is first seen in a saga” (this is how I first encountered this issue btw.)

Obviously the real issue is the no unhandled exceptions should exist, the unexpected part for me at the time was that I thought that the downstream from the put was considered unrelated and the exception was a surprise. That is now changed and I assume documented, how exactly would one prevent an exception from a render caused by a reducer triggered by a saga put from bubbling up into the saga? I mean, where could one put the extra catch?

**Comment by Andarist** [comment] 2019-09-10 10:53
For renders, you can implement ErrorBoundary, for reducers - not sure? middleware? Keep in mind that this in case of reducers can only help you in terms of logging etc, you probably should rethrow it anyway (or kill your app manually in the catch block)

**Comment by neurosnap** [comment] 2022-02-27 03:54
Closing due to inactivity.  If this is still an issue then please reply and I will reopen and try to help debug.  Thanks!

**Closed by neurosnap** 2022-02-27 03:54 UTC
