### ISSUE TITLE
How to test generators ifs efficiently with lot of effect?

### ISSUE THREAD

**Issue by henrikra** [redux-saga/redux-saga#678] opened 2016-12-09 07:59 UTC
Lets say I have generator like this:
```javascript
export function *fetchService() {
  while (true) {
    const fetchTask = yield fork(fetch);
    const {type} = yield take([
      actionTypes.FETCH_READY,
      actionTypes.FETCH_TIMEOUT,
      actionTypes.FETCH_ERROR,
    ]);
    if (type === actionTypes.FETCH_TIMEOUT || type === actionTypes.FETCH_ERROR) {
      yield cancel(fetchTask);
    }
    // over 15 different effects here
  }
}
```
I want to test all three possible actionTypes and go to all if branches. So is there efficient way of testing the ifs? Or do I really have to go through all 15 effect before I can test the if statement again?

**Comment by Andarist** [comment] 2016-12-10 00:24
It all depends on how you want to test and how much you would like to have tests coupled to the implementation. There is not (and probably wont be) official way of testing your complex sagas as it really comes down to your personal preference about testing in general.

**Comment by baldwmic** [comment] 2017-04-20 00:03
@henrikra when it comes to testing sagas, many people appear to be using a black-box testing approach to assert things happening.

you may consider looking at https://github.com/jimbol/generator-test-runner as an example of how to test sagas in a more developer friendly fashion

**Comment by ralphstodomingo** [comment] 2017-04-27 03:13
There's also https://github.com/jfairbank/redux-saga-test-plan.

**Comment by erikvold** [comment] 2017-07-16 22:34
@Andarist this seems like a dup of #518

**Comment by Andarist** [comment] 2017-07-17 08:51
@erikvold it seems so, many threads about testing approaches are spread on the issues unfortunately

duplicate of #518

**Closed by Andarist** 2017-07-17 08:51 UTC
