### ISSUE TITLE
What is the recommended way of using effects with the UMD bundle?

### ISSUE THREAD

**Issue by Aghassi** [redux-saga/redux-saga#1880] opened 2019-07-01 16:47 UTC
We are trying to leverage the UMD bundle for our applications, but we have users who are unable to import `redux-saga/effects` because currently we map `redux-saga` to the UMD bundle. I've been skimming the docs and I don't see a concrete way of how to use effects with the UMD bundle. It may be that I'm missing something, but if someone could point me in the right direction that would be great.

If effects is not suppose to be used with the UMD bundle, is there a way an `effects.umd.js` could be published so we could map `redux-saga/effects` to it?

**Comment by Andarist** [comment] 2019-07-01 18:18
UMD has slightly different module shape - defined [here](https://github.com/redux-saga/redux-saga/blob/6cac49788c2a81d3c32e3017e5dac6b8345a59e1/packages/redux-saga/src/index.umd.js).

You should be able to access effects like this:
```js
const { effects } = ReduxSaga

// ...
yield effects.put({ type: 'FOO' })
```

**Comment by spentacular** [comment] 2019-07-01 19:38
While developing locally webpack will pick up the `modules` bundle, but since it's marked as an external this means the module paths we are referencing will be broken when using the final UMD bundle in the browser.

**Comment by Aghassi** [comment] 2019-07-01 20:05
To clarify @spentacular point, we work in a microfrontend architecture (similar to https://single-spa.js.org). So when developers bundle, the import path may not resolve to anything since we mark it as externals on Webpack.

**Comment by Andarist** [comment] 2019-07-01 20:12
Hm, could you prepare a simple repository with your setup demonstrated? I'm not sure how do you author your source, what comes out of it, on what stage do you map (?) your imports to UMD bundles, and how exactly vendors are shared at runtime. I maybe could propose a solution for you then, but without this it's hard for me to imagine how exactly all of this ties together (even though I'm experiences with webpack, module system and all of that, havent been working with micro frontends though).

**Comment by spentacular** [comment] 2019-07-02 00:55
Hey @Andarist here's a tiny reproduction: https://github.com/spentacular/reduxsaga-example

The portion that's causing the problem is [here](https://github.com/spentacular/reduxsaga-example/blob/master/webpack.config.js#L25)

We don't use the UMD bundle for development, just the regular module package. But for the final production build `redux-saga` is on the window using the UMD package, which creates the error shown when running `yarn start`.

**Comment by Andarist** [comment] 2019-07-02 07:23
Your demo doesn't fail on effects entry though, but on the redux-saga itself:
```
Uncaught TypeError: redux_saga__WEBPACK_IMPORTED_MODULE_2___default(...) is not a function
    at Module../index.js (index.js:21)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
    at webpackUniversalModuleDefinition (universalModuleDefinition:7)
    at universalModuleDefinition:10
```

Could you include in the demo any other package which works for you like this?

**Comment by spentacular** [comment] 2019-07-02 15:16
I updated to also have a different external. I also fixed it so that the `redux-saga/effects` portion was the only one failing the lookup.

```
redux-saga.umd.min.js:1 TypeError: Cannot read property 'takeEvery' of undefined
    at mySaga$ (index.js:18)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at d (redux-saga.umd.min.js:1)
    at ot (redux-saga.umd.min.js:1)
    at redux-saga.umd.min.js:1
    at cn (redux-saga.umd.min.js:1)
    at ct (redux-saga.umd.min.js:1)
    at Function.i.run (redux-saga.umd.min.js:1)
```

I haven't found a way to reference the effects on both sides without the production one failing, since it's an internal reference to something AMD has already defined.

If `effects` had its own UMD bundle, even with something like `ReduxSagaEffects`, this would allow webpack to easily externalize it without UMD bundles needs to use a different reference.

**Comment by Andarist** [comment] 2019-07-02 20:16
I've published a new version which has dedicated UMD bundle for effects available i.e. here - https://unpkg.com/redux-saga@1.0.5/dist/redux-saga-effects.umd.min.js 

Effects code is duplicated in main UMD bundle (didnt want to make a breaking change), but those both bundles should work together just fine. Let me know if this resolves your issue.

**Comment by spentacular** [comment] 2019-07-03 01:27
@Andarist that works great! Thanks for helping out.

**Comment by Andarist** [comment] 2019-07-03 07:07
No problem 😄

**Closed by Andarist** 2019-07-03 07:07 UTC
