### ISSUE TITLE
Context makes it impossible to transparently wrap a Saga

### ISSUE THREAD

**Issue by saboya** [redux-saga/redux-saga#1280] opened 2017-12-04 00:42 UTC
Hello. I'm trying to implement a higher-order Saga to filter actions that the wrapped Saga receives. Since a simple `fork` would still be attached to the store middleware, thus receiving all the actions, I figured I would have to run the wrapped Saga outside the store middleware and pass all the actions to it, except the "undesired" ones.

This isn't so hard by itself, this is a working example that does exactly that:
```javascript
let sagaEventEmitter
const sagaEventsChannel = eventChannel(localEmitter => {
  sagaEventEmitter = localEmitter
  return () => {
    console.log('cleaning up eventChannel')
  }
})

function * handleSagaEvents () {
  while (true) {
    let action = yield take(sagaEventsChannel)
    yield put(action)
  }
}

function sagaWrapper (saga) {
  return function * (...args) {
    const sagaChannel = stdChannel()
    const sagaEventsTask = yield fork(handleSagaEvents)
    const sagaTask = runSaga(
      {
        channel: sagaChannel,
        dispatch: sagaEventEmitter,
      },
      saga,
      ...args,
    )

    while (sagaTask.isRunning()) {
      let action = yield take('*')

      switch (action.type) {
        case 'SOME_CUSTOM_ACTION':
          // do custom stuff instead of passing it along
          break
        default:
          // pass all other actions along
          yield sagaChannel.put(action)
          break
      }
    }
  }
}

export default sagaWrapper
```

However, if the wrapped Saga makes any `getContext` calls, this doesn't work. And since the API does not provide a call to get the whole context, there's not way to pass context down without knowing the key that the wrapped Saga will require in advance.

There's a way to get around this, but IMO it's way overcomplicated for something that could be a lot simpler:

```javascript
const contextCallChannel = channel()

let sagaEventEmitter
const sagaEventsChannel = eventChannel(localEmitter => {
  sagaEventEmitter = localEmitter
  return () => {
    console.log('cleaning up eventChannel')
  }
})

function * handleSagaEvents () {
  while (true) {
    let action = yield take(sagaEventsChannel)

    switch (action.type) {
      case 'GET_CONTEXT':
        yield put(contextCallChannel, yield getContext(action.payload))
        break
      default:
        yield put(action)
        break
    }
  }
}

function * handleContextCalls () {
  return yield take(contextCallChannel)
}

function sagaWrapper (saga) {
  return function * (...args) {
    // Fork it early because of handleContext stuff
    yield fork(handleSagaEvents)

    const sagaChannel = yield stdChannel()

    const handleContextMiddleware = next => effect => {
      if (effect.GET_CONTEXT) {
        sagaEventEmitter({ type: 'GET_CONTEXT', payload: effect.GET_CONTEXT })
        effect = call(handleContextCalls, effect.GET_CONTEXT)
      }
      next(effect)
    }

    const sagaTask = runSaga(
      {
        channel: sagaChannel,
        dispatch: sagaEventEmitter,
        effectMiddlewares: [handleContextMiddleware],
      },
      saga,
      ...args,
    )

    while (sagaTask.isRunning()) {
      let action = yield take('*')

      switch (action.type) {
        case 'SOME_CUSTOM_ACTION':
          // do custom stuff instead of passing it along
          break
        default:
          // pass all other actions along
          yield sagaChannel.put(action)
          break
      }
    }
  }
}

export default sagaWrapper
```

I don't know the best way to solve this, since I believe the reasons to hiding the context object are legitimate, but I also think this pattern is something that is desirable.

I may be missing something here, so I welcome any feedback on this.

Thanks for your hard work on this great library.

**Comment by Andarist** [comment] 2017-12-04 11:04
You could possibly handle your `handleContextMiddleware` in a slightly easier, but arguably more hacky, way - you could create a dummy task with `fork` which would attach itself to the parent in regular fashion and call `createdFork.getContext` instead wrapping this in a `call(handleContextCalls)` and using channel to get the result back.

Both solutions are far away from perfect though. I have a strong feeling that having [this](https://github.com/redux-saga/redux-saga/pull/1263) implemented and released would let you achieve your goal in a more straightforward way. OTOH you want your wrapped saga to be agnostic of any funky stuff going on and custom effects won't give you that. It seems that what you want is some sort of combination of:
- `effectMiddlewares` (for top level saga without need to use `runSaga` in a middle of execution tree)
- access to the formalized internal state from the `effectMiddlewares`, that way you could somehow resolve `take` effects with replaced `channel`

Or maybe it would even require creating a single custom effect of `fork` (used in the wrapper), which could create a task with custom `stdChannel`.

It's quite hard to say though at this point, your use case is quite specific and also quite interesting. If you have any suggestions how the saga runtime could ease such an integration I would be glad to review any proposals. For now I'd like to finish the mentioned PR (any input, review, comments highly appreciated!) and see afterwards if it helps you in any way.

Also it's really nice to see that you are using **v1-beta** already 🎉

**Comment by Andarist** [comment] 2017-12-04 11:08
It occured to me just now that with custom effects you would be able to create `getAllContext` and pass the result to the `runSaga`.

Still - ideally you wouldn't have to use `runSaga` directly.

**Comment by saboya** [comment] 2017-12-04 12:19
> You could possibly handle your handleContextMiddleware in a slightly easier, but arguably more hacky, way - you could create a dummy task with fork which would attach itself to the parent in regular fashion and call createdFork.getContext instead wrapping this in a call(handleContextCalls) and using channel to get the result back.

Yes, this would make it a bit less obfuscated. However, `Task` doesn't seem to expose `getContext`, only `setContext`, or am I missing something?

> I have a strong feeling that having [this](https://github.com/redux-saga/redux-saga/pull/1263) implemented and released would let you achieve your goal in a more straightforward way.

My comprehension of redux-saga's internals are not too strong, I'm gonna have to take a closer look to see what exactly that could enable :)

> Or maybe it would even require creating a single custom effect of fork (used in the wrapper), which could create a task with custom stdChannel.

This seems to be exactly what I want, and seems like the simpler solution.

> It's quite hard to say though at this point, your use case is quite specific and also quite interesting.

I think it's useful to be able to add functionality through higher-order function composition in general. I can't say this is a very common practice, but I think it could be useful in many situations. In this particular case I'm filtering actions based on refcounting actions, and I wanted to have this logic isolated because I use this in more than one place.

This could also be used to run a saga in a Web Worker / server-side in a agnostic way (although there are a lot of limitations in this case, especially with context, since there are no guarantees they are plain javascript objects).

> Also it's really nice to see that you are using v1-beta already :tada:

\o/ The new mutiCast channel is very nice, I'm already using it for some stuff.

**Comment by Andarist** [comment] 2017-12-04 12:32
> Yes, this would make it a bit less obfuscated. However, Task doesn't seem to expose getContext, only setContext, or am I missing something?

Oh, you are right 😄 Was quite sure both `getContext`/`setContext` are just proxying to Task's methods. I think when I have introduced those effects I had to expose a way to set top level context from outside the saga runtime and that's why I have added `setContext` method on `Task`. I could consider adding a sibling `getContext` method, would like to think of use cases first though. Obviously yours is one, but I'm wondering if there are any other - context was primarily implemented as way to share stuff within saga without having to pass it explicitly through call/fork arguments in nested saga trees. `getContext` method seems to escape this initial assumption, because it allows outside world to manipulate internal context.

> I think it's useful to be able to add functionality through higher-order function composition in general.

Couldnt agree more 😃 

> \o/ The new mutiCast channel is very nice, I'm already using it for some stuff.

Glad to hear that you enjoy it! :)

**Comment by jrnail23** [comment] 2017-12-13 17:30
@Andarist, am I correct to interpret this discussion as saying there's not currently (as of v0.16) a clean way to do compose saga functionality via higher order functions?

Also, is it currently possible to create custom effects?  If so, can you please point me to any docs/examples/etc. for them?

**Comment by saboya** [comment] 2017-12-13 20:59
@jrnail23 It is possible. however there are caveats if your sagas are not pure.

The reason that context makes everything messier is because context variables are essentially implicit arguments to sagas. In strictly pure functions, you wouldn't use context at all, instead passing them explicitly when running your sagas.

Also, for my use case I needed to filter the actions that the  wrapped saga receives. If you have no such requirement, a simple `fork` would be enough to spawn the wrapped saga, which would handle the context issue since forked sagas inherit context.

**Comment by Andarist** [comment] 2017-12-13 21:14
> @Andarist, am I correct to interpret this discussion as saying there's not currently (as of v0.16) a clean way to do compose saga functionality via higher order functions?

It is very much possible, example:
```js
import Backoff from 'backo2'

export function* backoffRetry(min, max, saga, ...args) {
	const backoff = new Backoff({
		min,
		max,
	})
	for (;;) {
		try {
			const result = yield call(saga, ...args)
			return result
		} catch (err) {
			yield call(delay, backoff.duration())
		}
	}
}

// with such example usage
const answer = yield call(backoffRetry, 100, 20000, mightThrowSaga)
```

The issue described here is caused by some specific requirements - described by @saboya above.

> Also, is it currently possible to create custom effects? If so, can you please point me to any docs/examples/etc. for them?

Not yet, but I would like to make custom effects possible.

**Comment by mpeyper** [comment] 2017-12-21 12:24
Just wanted to add my interest in this discussion/feature.  I'm the author of [redux-subspace](https://github.com/ioof-holdings/redux-subspace) which is a library for creating isolated sub-stores for micro-frontends that are still actually part of a global redux store.

Basically, the sub-stores isolate state and actions that are raised from within and as of version 2 it supports a bunch of redux middleware, including redux-saga.

The catch with redux-saga is that I need to intercept the action and strip off it's namespace on the way in, and intercept any `put` effects and apply the namespace on the way out.  To add further complexity, any `select` effects must only return the sub-store's state.  

Similarly to @saboya, I figured I would run the subspaced saga outside of the global store's middleware and create a seperate saga runtime for the substore (the substore already handles all of the complexity described above).  [Here is my implementation](https://github.com/ioof-holdings/redux-subspace/blob/master/packages/redux-subspace-saga/src/sagas/subspaced.js):

```
import { runSaga } from 'redux-saga'
import { getContext, takeEvery } from 'redux-saga/effects'
import { subspace } from 'redux-subspace'
import provideStore from './provideStore'

const emitter = () => {
  const subscribers = []

  function subscribe(sub) {
    subscribers.push(sub)
    return () => {
      subscribers.splice(subscribers.indexOf(sub), 1)
    }
  }

  function emit(item) {
    const arr = subscribers.slice()
    for (var i = 0, len = arr.length i < len i++) {
      arr[i](item)
    }
  }

  return {
    subscribe,
    emit
  }
}

const subspaced = (mapState, namespace) => {
  const subspaceDecorator = subspace(mapState, namespace)

  return saga => {
    return function* wrappedSaga() {
      const parentStore = yield getContext('store')

      const sagaEmitter = emitter()

      const store = {
        ...subspaceDecorator(parentStore),
        subscribe: sagaEmitter.subscribe
      }

      runSaga(store, provideStore(store)(saga))

      yield takeEvery('*', function*(action) {
        store.processAction(action, sagaEmitter.emit)
        yield
      })
    }
  }
}

export default subspaced
```

This has worked fine for us for a while now (but I do welcome any comments or feedback on improving the implementation), but we are running into an issue now trying to pass context from a parent outside the subspace to a child inside, as the sagas do not share context.

Interestingly, I've already run into this before with the `store` value passed down the context to wrapping in subspaces, but I was able to overcome it here by transferring it to the new saga's context (that's what `provideStore` does).

Ideally, I would like to transfer the whole context to the other saga runtime, but as previously stated in this thread, that does not appear to be currently possible.

I was wondering how you would feel about changing [`runGetContextEffect `](https://github.com/redux-saga/redux-saga/blob/60f4787871c56cb37028270ee39e4192d7b55a3f/src/internal/proc.js#L693-L695) to be something like:

```
function runGetContextEffect(prop, cb) {
  if (prop) {
    cb(taskContext[prop])
  } else {
    if (isArray(taskContext)) {
      cb[ ...taskContext ])
    } else if (isObject(taskContext) {
      cb({ ...taskContext })
    } else {
      cb(taskContext)
    }
  }
}
```

_(Note: we can squabble of what `isArray` and `isObject` should look like later...)_

This should allow retrieval of the full context that I can the transfer across.

Thoughts?

**Comment by Andarist** [comment] 2018-07-02 20:16
@mpeyper ur proposal with spread would actually just copy "one level" of the context, saga contexts are chained together using prototype chain (thanks to `Object.create`) and spread wont do such a deep copy.

What would be ur desired behaviour? To fork a saga (preserve context, it being linked to a parent so preserving error/cancel propagation) just with namespaced select/put effects?

**Comment by mpeyper** [comment] 2018-07-02 23:51
Hi @Andarist,

Almost.  

The use case is to wrap a saga and filter then modify actions that `take` effects (and variants of) would receive (generally this will be actions that have a matching namespace, but there are other reasons why the action would be allowed through, and modify them so that the namespace has been removed), present a sub-state to the selector of `select` effects and namespace any actions created from `put` effects (and variants of).

To add a complication, the wrapped saga should be able to be written without any knowledge of being wrapped and could work if it was run in an unmodified saga middleware.

To add another complication, the subspaced sagas need to be infinitely nestable.

Does that all make sense?

**Comment by Andarist** [comment] 2018-07-07 21:00
Yeah - it makes sense. Preserving context wouldn't be really that hard, but keeping error/cancellation propagation in place and at the same time having configuration ([env nowadays](https://github.com/redux-saga/redux-saga/blob/8e1a6c153ea03adc2a46e8c1cf6f3d8395a07a87/packages/core/src/internal/runSaga.js#L76-L84)) replaced for the subtree (to support namespacing) is not that easy - API-wise. I'd really like to avoid exposing some setters/getters pairs for those internal things.

I doubt we'll tackle this problem any time soon - but if you have any ideas how we could make this supported (what the API would look like?) I'd be happy to discuss possibilities.

**Comment by mpeyper** [comment] 2018-07-07 21:35
I noticed there is an middleware feature just above the environment section
you linked. Is there more documentation on that anywhere (I can't spot any
scanning the docs)?

**Comment by Andarist** [comment] 2018-09-03 22:00
> I noticed there is an effect middleware feature just above the env section you linked. Is there more documentation on that anywhere (I can't spot any scanning the docs)?
> I'm wondering if it can be used to intercept the take, select and put effects?

I don't think we have any docs for this (yet), but yes - it's possible to intercept any effect using this feature.

**Comment by Alxandr** [comment] 2019-03-01 07:43
There should be an API that allows you to fork/spawn a child-saga with a different env. In my case, I would like to override the main channel (which would also allow for filtering/selecting events). Specifically, I currently do something like this:

```js
yield addHandler('someEventName', function*(returnPut) {
  yield returnPut(1);
  yield returnPut(2);
});

// somewhere else
const results = yield collect('someEventName');
// 1, 2
```

**Comment by neurosnap** [comment] 2022-02-27 04:16
Closing this issue due to inactivity.  If anyone feels like this discussion should continue, I would suggest a GH discussion.  Thanks!

**Closed by neurosnap** 2022-02-27 04:16 UTC
Labels: discussion
