### ISSUE TITLE
select does not return new model when yielded after put

### ISSUE THREAD

**Issue by krzysztofpniak** [redux-saga/redux-saga#966] opened 2017-05-05 11:15 UTC
This code does NOT work (and I think it should):
```js
yield put({type: 'someAction'}); //action that triggers model modification in updater
const newModel = yield select(m => m); //newModel contains old model
```

This code does NOT work:
```js
yield put.resolve({type: 'someAction'}); //action that triggers model modification in updater
const newModel = yield select(m => m); //newModel contains old model
```

This code DOES work:
```js
yield put({type: 'someAction'}); //action that triggers model modification in updater
yield delay(1);
const newModel = yield select(m => m); //newModel contains what it should without delay
```

I'm using version 0.15.3

**Comment by neurosnap** [comment] 2017-05-05 11:40
According to: https://redux-saga.js.org/docs/api/#putresolveaction

It looks like you need to add some middleware to make the redux `dispatch` return a promise.

Here's the code: https://github.com/redux-saga/redux-saga/blob/master/src/internal/proc.js#L448

**Comment by krzysztofpniak** [comment] 2017-05-05 11:45
@neurosnap what about the first one?

**Comment by Andarist** [comment] 2017-05-05 12:25
> This code does NOT work (and I think it should):
> // ...
> @neurosnap what about the first one?

if your action triggers update asynchronously somehow then its expected behaviour, it shouldnt be yet updated when selecting in this snippet

**Comment by krzysztofpniak** [comment] 2017-05-05 12:40
@Andarist my updater isn't asynchronous

**Comment by Andarist** [comment] 2017-05-05 13:06
does any async happen between `yield put({type: 'someAction'});` and `const newModel = yield select(m => m);`? Could u reproduce issue on something like webpackbin?

**Comment by krzysztofpniak** [comment] 2017-05-05 13:33
Really sorry, I tried to reproduce it in webpackbin and it works. It looks like other middleware causes my problem.

**Comment by Andarist** [comment] 2017-05-05 14:17
Going to close this issue then, if you have any other questions - just ask :)

**Closed** 2017-10-09 12:53 UTC
Labels: question
