### ISSUE TITLE
TypeScript `put(channel, action)` widening to allow null

### ISSUE THREAD

**Issue by bbil** [redux-saga/redux-saga#2110] opened 2020-08-25 00:09 UTC
#### Description of the bug/issue

It appears that in some cases, the TypeScript definitions of the `put` variant for channels will widen the type to include `| null`. This is problematic because of [#396](https://github.com/redux-saga/redux-saga/issues/396). In the case I was working on, I had a type that was nullable, and no error was shown when using `put`. This should not be allowed for the action parameter, as it is very clear in the documentation (copied here for reference):

> Note: You need to sanitize your event sources as to not pass null or undefined through the event channel. While it's fine to pass numbers through, we'd recommend structuring your event channel data like your redux actions. { number } over number.

I also did a quick check and `| undefined` has the same issue, widening the type of action with `| undefined`.

Note: manually adding the type to the call of `put` will force the type to be correct, and will cause the expected error.
e.g.
```
const numberChannel: Channel<number> = yield call(channel);
const result= getResult(); // inferred type of result: number | null
yield put<number>(channel, result);

Argument of type 'number | null' is not assignable to parameter of type 'number | END'.
  Type 'null' is not assignable to type 'number | END'
```

#### Steps to reproduce the bug/issue

1. Have a nullable type
2. Have a channel, that takes the type (without null) -- `Channel<number>`
3. use `yield put(channel, nullableVariable)`

### Actual results

Code compiles and causes a runtime issue.

### The Expected results

Code should not compile, as null/undefined is not allowed.

Expect the same error message as if the generic argument was specified manually:

> Argument of type 'number | null' is not assignable to parameter of type 'number | END'.
  Type 'null' is not assignable to type 'number | END'

### Environment information
redux-saga version: 1.1.3
typescript version: 3.7.5

**Comment by bbil** [comment] 2020-08-25 00:10
I wrote this up at the end of the work day, so I haven't created a minimal example or even thought about how to fix. First... food.

**Comment by bbil** [comment] 2020-08-25 00:34
Doing some quick tests locally, and adding `NonNullable` around the `T` argument seems to force it to work:

```
export function put<T>(channel: PuttableChannel<T>, action: NonNullable<T> | END): ChannelPutEffect<T>
```

I have no idea if this is a standard thng to do in situations like this...

**Comment by Andarist** [comment] 2020-08-25 09:27
Isn't this by any chance caused by not using `strictNullChecks` on your side? Could you create a runnable repro case for me? Only with such, I'm able to assess your issue.

**Comment by bbil** [comment] 2020-08-25 14:47
I can confirm that `strictNullChecks` is enabled. I can create a repo, but may take me a bit, busy with other stuff right now.

**Comment by neurosnap** [comment] 2022-12-15 15:23
Greetings!  Since we don't have an example we can run, it's hard for us to help.  Once you submit a reproducible case we can continue to investigate.  Closing for now.

**Closed by neurosnap** 2022-12-15 15:23 UTC
Labels: bug, help wanted
