### ISSUE TITLE
'CHANNEL_END' is not exported

### ISSUE THREAD

**Issue by ok111net** [redux-saga/redux-saga#765] opened 2017-01-14 13:04 UTC
the v 0.14.2
when i user rollup.js dist the js,it show:
Error: 'CHANNEL_END' is not exported by 'H:\web\ruying\node_modules\redux-saga\es\internal\channel.js' (imported by 'H:\web\ruying\node_modules\redux-saga\es\utils.js');

i find the code 'export { CHANNEL_END } from './internal/channel';', in  'redux-saga\es\utils.js' line 3 err.
 './internal/channel' is not imported CHANNEL_END.

**Comment by Andarist** [comment] 2017-01-14 23:44
Gonna close the issue as this is a duplicate of [this](https://github.com/redux-saga/redux-saga/issues/689). Please read [my comment](https://github.com/redux-saga/redux-saga/issues/689#issuecomment-272661955) in the other thread.

If you have any further questions about this, please put them in there.

**Closed by Andarist** 2017-01-14 23:44 UTC
