### ISSUE TITLE
Compatibility problem with release 1.0

### ISSUE THREAD

**Issue by JacquesBonet** [redux-saga/redux-saga#1739] opened 2019-01-23 07:06 UTC
#### Description of the bug/issue

I can't use redux-saga 1.0 with my application which use react-redux 6.x and connected-react-router 6.x
  ==> The effects are not called

I don't have problem with redux-saga ~0.16.0

### The Expected results

Effects are called

### Environment information

- redux-saga version 1.0.0
- react-redux 6.0.0
- connected-react-router 6.2.2
- tsc: 3.2.2

**Comment by Andarist** [comment] 2019-01-23 09:40
Could you provide a self-contained reproduction case? Preferably on something like codesandbox.io

**Comment by vclav** [comment] 2019-01-23 17:47
I can confirm this behavior. It might be related to `connected-react-router`. Given code

```
import { push } from 'connected-react-router';
import { put } from 'redux-saga/effects';

function *navigateTask() {
    yield put(push('/path'))
}
```

the actions is logged into Redux debugger, but it is not intercept by *connected-react-router/middleware*.

**Comment by Andarist** [comment] 2019-01-23 18:14
Just to repeat myself:
> Could you provide a self-contained reproduction case? Preferably on something like codesandbox.io

You must understand that any maintainer's time is really limited (I have a day job) and I just can't try to replicate your issues on my own. It would be way faster if you could prepare a repro case and then I could dive straight away into debugging and fixing the issue.

**Comment by JacquesBonet** [comment] 2019-01-24 00:16
I think its another problem for me.
I use redux_starter_kit which provide a function configureStore() which configure redux dev toolslike vclav say(https://github.com/reduxjs/redux-starter-kit/blob/0e139e9ebbbf4f5f6e55280046be5372524e06b3/src/configureStore.ts) .

I test tomorrow

**Comment by vclav** [comment] 2019-01-24 08:11
@JacquesBonet I've attached my own middleware just above `connected-react-router` to observe actions passed to it, you can try it also, the simple log middleware is

```
state => next => action => (console.log('MIDDLEWARE ACTION', action), next(action))
```

and you will see if the actions are not the cause

also, quite common problem in my codebase was deprecation of yielding multiple effects as array `yield [put(...), put(...)]`, you must now use `all` effect like `yield all([...])`. But without isolated example as @Andarist suggested, all my advices are only blind shots.

**Comment by JacquesBonet** [comment] 2019-01-26 06:37
I tested with redux-saga 1.0, I have an exception:

     Attempted import error: 'delay' is not exported from 'redux-saga'.

Delay is declared here (was declared in redux-saga on te 0.16)

     import { call, cancel, delay, fork, put, takeEvery } from 'redux-saga/effects';

I cleaned the cache, rebuild all same error. Don't understand.




Jacques

**Comment by Andarist** [comment] 2019-01-26 09:39
You have to have `import { delay } from 'redux-saga'` somewhere, but it's available as effect now - so you can import it from `redux-saga/effects`

**Comment by Andarist** [comment] 2019-01-26 12:04
Glad you got it working. Closing this then

**Closed by Andarist** 2019-01-26 12:04 UTC
