### ISSUE TITLE
Any way to wait for sagas in high level integration tests?

### ISSUE THREAD

**Issue by nathanmarks** [redux-saga/redux-saga#1312] opened 2018-01-19 14:32 UTC
I have some very high level integration tests in my application that I'm running using jest/node/jsdom and I'm mocking HTTP requests using nock.

Is there any sort of equivalent test helper to something like:

```
export const flushAsync = () => new Promise((resolve) => setTimeout(resolve, 0));
```

That I can implement that would allow me to reliably wait until my sagas have finished running before making assertions in my tests?

(note, the above does work for flushing promises in other cases, but with my setup, I found I had to increase the timeout higher than ~5ms to wait for my sagas to be completed).

I did look at https://github.com/redux-saga/redux-saga/issues/187 but it didn't help me achieve what I'm trying to do.

**Comment by Andarist** [comment] 2018-01-19 14:58
You should be able to do something like this
```js
const saga = sagaMiddleware.run(someSaga)
saga.done.then(() => {
  // assertions
})
```

**Comment by nathanmarks** [comment] 2018-01-19 15:14
@Andarist It doesn't seem to be fulfilling. The saga returns `true` for `isRunning()` but `done.then(() => ...)` is never called.

```
      console.log(store.injectedSagas.signin.task.isRunning()); // true

      store.injectedSagas.signin.task.done.then(() => {
        expect(usernameRequest.isDone()); // never called
        done();
      });
```

if you're wondering how I'm getting the result of `sagaMiddleware.run(someSaga)` as you see above, see here:
https://github.com/react-boilerplate/react-boilerplate/blob/master/app/configureStore.js#L47
https://github.com/react-boilerplate/react-boilerplate/blob/master/app/utils/sagaInjectors.js#L54

**Comment by nathanmarks** [comment] 2018-01-19 15:18
@Andarist Also, `isRunning()` is still `true` even with the effects have finished running.

I suppose I miscommunicated my need: how do I wait for the running effects to be completed?

**Comment by Andarist** [comment] 2018-01-19 17:05
Does your saga contain any "infinite" tasks? Like `takeEvery`/`takeLatest`/`throttle` or custom `while (true)` loops? If yes then do this

```js
import { END } from 'redux-saga'

store.dispatch(END)
```
at some point of your test (when you know that you want to do assertions)

**Comment by nathanmarks** [comment] 2018-01-19 17:23
@Andarist 

Thanks for the tip, that's definitely useful for some use cases! I am using `takeEvery` and `takeLatest`.

The problem I'm having using it in this specific use case, is that I have one effect that dispatches a `SUCCESS` action, and another side effect as a result of that success. When I dispatch `END`, that last side effect doesn't run.

Is there a better way to set up these side effects so that they all run even after `END` is dispatched?

**Comment by Andarist** [comment] 2018-01-20 10:56
You'd have to show some code and explain the flow, hard to advise without seeing specifics of the problem.

**Comment by epiqueras** [comment] 2018-01-23 05:51
@Andarist 
The problem happens when waiting for a put or put.resolve effect to take place.

Here is some code/flow to illustrate:

I have a saga with `takeLatest` that waits for a FETCH action to start an async network request, wait for it to resolve and dispatch a RECEIVE action with the result.

In my tests I set up the store, middleware, etc, and mount the app.

Then I trigger the FETCH and wait like this:
```js
// Flush all promises
await new Promise(resolve => setImmediate(resolve))
// Tell sagas that we are stopping
integration.store.dispatch(END)
// Wait for saga to terminate
await integration.rootSagaTask.done

// Test assertions
```

The problem is that put or put.resolve never finish. I can verify in the saga that the network request resolved and the payload was valid, but the saga gets stuck on the first put and then terminates without continuing.

If I use put and not put.resolve, I also get an error on react-dom where document is undefined when trying to use createEvent. I guess this is code running after jsdom is torn down.

Any ideas?

**Comment by Andarist** [comment] 2018-01-24 12:19
Could u setup a simple repro on something like codesandbox? or as separate repository? I will be able to debug this quickly then and let you know how it can be handled.

Which version of `redux-saga` do you use? Also what kind of code is following a faulty `put`?

**Comment by maximderbin** [comment] 2018-02-13 02:29
https://github.com/redux-saga/redux-saga/issues/904 linking 2 related issues

**Comment by thchia** [comment] 2018-02-20 10:32
I have a question related to this issue.

In my project I have a root saga that uses a  `yield all([ takeLatest(...) ])` pattern.

One of the sagas triggered by the `takeLatest` is a looping function - it does something, delays for a specified period and then does that thing again. This appears to block the `done` from resolving. I'm not really sure why this is - is it because the while loop containing a `call` to delay is preventing the saga from terminating?

**Comment by Andarist** [comment] 2018-02-21 18:16
`done` can resolve only if your saga ends its execution. At the same time every attached task (`call`ed, `fork`ed - where `takeLatest` etc use `fork` under the hood) must end before the parent resolves.

In other words - whole task of trees has to finish first.

**Closed** 2018-09-03 21:54 UTC
Labels: question

**Comment by challet** [comment] 2024-10-25 14:56
> You should be able to do something like this
> 
> ```js
> const saga = sagaMiddleware.run(someSaga)
> saga.done.then(() => {
>   // assertions
> })
> ```

For future reference, the `done` member seems to be now a method `toPromise()` : https://redux-saga.js.org/docs/api#task
