### ISSUE TITLE
redux-saga not working in release configuration with react-native 0.50.1

### ISSUE THREAD

**Issue by ianhowe76** [redux-saga/redux-saga#1305] opened 2018-01-11 10:30 UTC
I am creating an app using react-native and redux-saga

When I build the app in debug configuration everything is fine. However, when I build in release configuration redux-saga is not working i.e. none of the sagas intercept the action using takeLatest/takeEvery

Downgrading to react-native 0.49.2 fixes the problem.

I am not sure if this is an issue on your side or react-native.

Any help would be appreciated

Package details are below:

```
react-native: 0.50.1
react: 16.0.0
redux-saga: 0.16.0
```

**Comment by j-wang** [comment] 2018-01-16 04:28
We're on RN 0.51.0 and and redux-saga 1.0.0-beta.0 and we're not having a problem with takeLatest/takeEvery running.

One headache we are running into (which might be worth a separate issue) is that saga crashes DO kill all `takeX`s, but happen silently on production. A guess is maybe it's either not having version 1 of redux-saga or maybe something's silently killing sagas on release?

**Comment by Andarist** [comment] 2018-01-16 05:01
@j-wang it shouldnt happen silently, if sagas fail the redux-saga just kills itself (well, it's part of the task tree - which in most cases means the whole tree). Does it happen in development for you? Maybe not silently but with a warning?

@ianhowe76 You'd really have to debug this a little bit more to see what happens, your description is too vague without any info that we could have used for debugging this. I find people often having problems with broken react-native presets and such stuff, maybe you could check and confirm your setup?

**Comment by j-wang** [comment] 2018-01-16 19:18
@Andarist Let me see if I can put together a minimum case, but just to clarify, I think the behavior I'm trying to describe **is** what you're describing right now?

It's silent in the sense that what would be a "red screen" in debug becomes nothing at all in production/release (as such, nothing runs because the whole tree / root saga is dead... but the app is still running, just with no sagas working). 

This has bitten me at least more than a few times, since I don't expect sagas to just be gone and I don't have code handling that. If you have a suggestion for how to handle it—even forcing an overall app crash—I'd love to know. Also, happy to continue this in another issue if it's drifted far afield of the original subject. I just figured that it *might* be what @ianhowe76 might have encountered, since it sounds similar to some of my own confusion when I ran across it.

**Comment by Andarist** [comment] 2018-01-18 12:37
Yeah, many people implements some restarting mechanisms - although such approach should be used with caution, your saga might easily die again and again, creating somewhat infinite loop (not necessarily synchronous) of restarting.

As mentioned this is expected behaviour, preferrably you should handle any possible errors yourself. In general sense it is unwise to just restart things at any cost, because your app has landed in unknown state and you cannot possibly know how to fix it at runtime and this might lead to worse UX. 

If you want to guard urself, I'd advise organizing your sagas on per "feature" basis and wrap each feature with something like `safe`:
```js
const safe = (saga, ...args) => {
  try {
    yield call(saga, ...args)
  } catch (err) { /* just let it die */ }
}
```

and use it like:
```js
yield fork(safe, featureA, arg1)
yield fork(safe, featureB, arg2)
```

That way in case of an unexpeted error your app will become unusable only partially and you won't cause weird auto restarts.

That's my opinion though but it lines up with many people's opinions (react@16 unmounts your whole tree too in case of an error in render, unless u specify `componentDidCatch` somewhere)

**Comment by Andarist** [comment] 2018-01-18 23:49
> I suppose my original expectation here was closer to redux-observable and React Native itself, where "red screens" cause the entire app to crash.

Interesting, Im wondering now what's better for the overall app - to kill all sagas or to crash an entire app? 🤔

**Closed** 2018-07-05 07:37 UTC
