### ISSUE TITLE
Examples • npm ERR!

### ISSUE THREAD

**Issue by Viral-Inc** [redux-saga/redux-saga#997] opened 2017-05-21 18:38 UTC
Hi :) if I follow the instructions under **Building examples from sources**, then:

- if I try running the **_real-world_** example from the _**redux-saga**_ directory, this fails: 

```
npm --prefix examples/real-world install examples/real-world && cross-env BABEL_ENV=cjs node --require babel-register examples/real-world/server.js
```

- if I try running the **_real-world_** example from the _**real-world**_ directory, this fails:
```
node --require babel-register server.js
```

**Comment by Andarist** [comment] 2017-05-21 19:21
thanks for pointing this out, we'll try to fix those asap

**Comment by Andarist** [comment] 2017-05-22 16:43
could u share ur configuration? os, node, npm versions etc? while something is broken in this example (app-wise) it compiles just fine on my machine and im able to run it

**Comment by Viral-Inc** [comment] 2017-05-22 16:57
Yup: macOS Sierra 10.12.5, npm: 4.2.0, node 7.10.0

**Comment by Andarist** [comment] 2017-05-27 18:48
@Viral-Inc I literally cannot reproduce this, everything is fine on my machine. Are u able to investigate this?

**Comment by Viral-Inc** [comment] 2017-05-28 16:59
@Andarist I tried to a little bit but there were too many things involved that I don't know enough about, yet :(

[I'm having fun with redux-saga now anyway - I'll just hope my issue with the examples was an anomaly.]

**Comment by Andarist** [comment] 2017-05-28 18:57
Ill close this issue then, as I cannot reproduce it anyway. Hope you enjoy saga nevertheless!

**Closed by Andarist** 2017-05-28 18:57 UTC
Labels: bug, examples
