### ISSUE TITLE
Bundling with Rollup fails due to missing export

### ISSUE THREAD

**Issue by zech** [redux-saga/redux-saga#689] opened 2016-12-12 13:10 UTC
Hello,

i'm trying to bundle my project using redux-saga and stumbled upon an issue.

using the node-resolve plugin for rollup and the `{ jsnext: true }` option gives me the following error:

`'CHANNEL_END' is not exported by '$PATH_TO_PROJECT$\node_modules\redux-saga\es\internal\io.js' (imported by '$PATH_TO_PROJECT$\node_modules\redux-saga\es\utils.js')
Error: 'CHANNEL_END' is not exported by '$PATH_TO_PROJECT$\node_modules\redux-saga\es\internal\io.js' (imported by '$PATH_TO_PROJECT$\node_modules\redux-saga\es\utils.js')
    at Module.traceExport ($PATH_TO_PROJECT$\node_modules\rollup\src\Module.js:376:17)
    ...`

Looking at the `es/internal/io.js` module there is no export for this but the `es/utils.js` re-exports this constant.

**es/utils.js**
`export { CHANNEL_END, asEffect } from './internal/io';`

Setting the `{ jsnext: false }` option solves the issue as a workaround but also disables all other es6 imports.

Did I miss something or is this a small bug?

Thanks in advance.

**Comment by Andarist** [comment] 2016-12-12 15:01
That's probably a bug, PR is on the way. Fix should be published in a following week, but till this time I would advice to use a forked repo (from the tag you are using right now) with the fix included. Sorry for the problem.

I would appreciate also if you can let us know if this fix helps you.

**Comment by zech** [comment] 2016-12-13 14:10
Thank you. The fix in your PR works as intended.

Aside from this i've got an issue importing effects as stated in the documentation when using the jsnext flag.

I had to change this:

`import { call, put } from "redux-saga/effects";`

to this:

`import { call, put } from "redux-saga/es/effects";`

At least i did not find this in documentation but is this the way it should be?

**Comment by Andarist** [comment] 2016-12-13 14:17
Unfortunately, I'm not familiar how Rollup bundling works and what should `jsnext` method do. Could you try to explain those a little?

Would you compare our distribution system with some other libs which are bundled with webpack and do not cause you any problems? Then we could start from this comparison and workout the solution.

**Comment by Andarist** [comment] 2016-12-13 15:06
from what I see we have appropriate entry in our `package.json`, just in other order, but that shouldnt be a problem
```
  "main": "lib/index.js",
  "jsnext:main": "es/index.js",
```

Ill wait for the comparison, as it might be really helpful in tackling this.

**Comment by zech** [comment] 2016-12-13 17:06
I've had a look around my currently used packages and I cannot find another usecase like this. But the more i think about this i think this is more or less related to the node-resolve plugin.

You cannot put both files (es5 & 6) within the same folder therefore the bundler plugin should respect the subfolder defined in the "jsnext:main" node. But it currently does not as you can see here:

https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L47

I do not know if it is a common practice to have submodules like the effects in the same folder because or re-export it as a named export. But if it is then this should be handled by the bundler.

Maybe I should open an issue over there.

**Comment by Andarist** [comment] 2016-12-13 17:21
could you create a test repo for me so I could play a little bit with the settings? would appreciate for instructions how to reproduce too

**Comment by zech** [comment] 2016-12-13 18:34
Does this one help?

https://github.com/zech/rollup-redux-saga

**Comment by Andarist** [comment] 2016-12-13 20:48
cool, thanks for those, gonna play around with it some time later!

**Comment by Andarist** [comment] 2016-12-14 12:19
Ok, I think I know why this happens, but aint sure how it should be solved.

1. `redux-saga/effects` is interpreted as node_module, so its traversing the directory tree and searches for that using this
https://github.com/substack/node-resolve/blob/7f0ce871b6d2b5cb2082b04cd72ddd4055cb7a05/lib/async.js#L172
2. its checking always if the found thing is a dir or file and act accordingly
3. it finds this https://github.com/yelouafi/redux-saga/blob/250e722419f9fcaade729c51aaf5d97a3de2b16a/effects.js and loads accordingly which in your case unfortunately points at the wrong file (from the `lib`) folder

In case of `redux-saga` itself it finds a correct directory and rollup later concatanates path with `jsnext:main` option. But its not working with `effects.js` for quite obvious reasons.

Ill try to reach out to rollup users so it can be handled in a better way.

@yelouafi 
I've always wondered about dir structure in the repo, could you elaborate a little bit more on it? Ive always assumed that `webpack` when importing `redux-saga/effects` is reaching for `./lib/effects.js` but it might seem (didnt check it though) that its reaching for `./effects.js` and this only acts as a 'proxy' to the beforementioned file. Its kinda non obvious at first and Im wondering if maybe it could be somehow organised better as this 'proxy' seems a little bit hacky

**Comment by yelouafi** [comment] 2016-12-14 12:34
see https://github.com/yelouafi/redux-saga/issues/70#issuecomment-182545609

**Comment by Andarist** [comment] 2016-12-14 12:55
Hm, so the solution would be to access a `jsnext` setting somehow and `require` this conditionally. Kinda clunky and aint sure if possible yet. Gonna search for possibilities later.

@zech 
For the time being I would use `effects` like this, until the issue is resolved better.
```javascript
import { delay, effects } from 'redux-saga'
const { call } = effects

function* saga() {
  yield call(delay, 1000)
}
```

**Comment by zech** [comment] 2016-12-14 12:58
Thanks,

currently i'm using

`import { effects } from "redux-saga/es/effects";`

I don't know if this is better or not. At least it works.

**Comment by Andarist** [comment] 2016-12-14 13:32
its more tied to the internal directory structure (which rather wont change ;) but still)

However as both are working, feel free to use whichever is more convenient for you.

**Comment by nktssh** [comment] 2016-12-25 09:44
was this fixes in [v0.14.0](https://github.com/yelouafi/redux-saga/releases/tag/v0.14.0) ?

**Comment by Andarist** [comment] 2016-12-25 09:58
It depends - v0.14.0 fixed wrong `CHANNEL_END` export

But the issue of importing `redux-saga/effects` within rollup is still not resolved. The best I've come with is [this](https://github.com/rollup/rollup/issues/1149#issuecomment-268743937), where possibly in the future we could switch the default to es6 modules once rollup/webpack2 adoption increase and make the reverse fallback to the cjs module format for webpack1 users.

WDYT? cc @zech @nktssh @yelouafi

**Comment by zech** [comment] 2016-12-25 11:15
Regarding `CHANNEL_END` after the update i've still got the same issue but now in another file:

```
'CHANNEL_END' is not exported by '$PATH_TO_PROJECT$\rollup-redux-saga\node_modules\redux-saga\es\internal\channel.js' (imported by '$PATH_TO_PROJECT$\rollup-redux-saga\node_modules\redux-saga\es\utils.js')
```

As stated `internal\channel.js` has no export for `CHANNEL_END`.


Importing the 'right' `redux-saga/effects` by defining a new environment variable like `JSNEXT=true` looks clumsy to me to be honest but may work i think.

I think documenting the right import path for ES6 users will be sufficient. Unfortunately i don't know if this is limited to rollup. I've never used Webpack before.

Maybe it's an option for future releases to reorganize the `redux-saga` module structure or go all JSNEXT ;-)

**Comment by nktssh** [comment] 2016-12-25 11:28
bug with wrong import doesn't affect  webpack 1 and webpack 2 users - use both of them on different project, all as expected.

the main problem is to have 2 entry points while all build systems expect only 1 main file.
At least two approaches coming to my mind:
* make 1 entry point
* split `redux-saga` package into two: `redux-saga-core` and `redux-saga-effects` (naming is just example)

**Comment by zech** [comment] 2016-12-25 12:16
@nktssh Which entrypoint is webpack 1/2 using? I guess it uses the normal `main` node in package.json as an entry point.

With rollup you can configure `jsnext:main` or `main` as an entry point. It defaults to the `main` entrypoint as you can see here: https://github.com/rollup/rollup-plugin-node-resolve

Configuring it with `jsnext: false` works of course but this forces rollup to use the es5 standard for all other node modules as well.

**Comment by nktssh** [comment] 2016-12-25 12:25
@zech it depends on webpack config. You can configure it to use `jsnext:main` or `main`.
With `main` webpack will use "lib" folder and with `jsnext:main` it will use "es" for main file and "lib/effects" for separate import.
It will just not throw error and silently use "lib/effects".
So, the problem is still exist but silently. Agree, it's not a solution rather that a cheap workaround.

**Comment by Andarist** [comment] 2016-12-25 12:36
@zech 
Ye, you are right, I got confused a little bit and changed the initial fix, gonna straighten thing up, just need to establish what should be in fact be exported as there are like 2 or 3 similar things, some internal. Sorry for the confustion.

Please read [this explanation](https://github.com/rollup/rollup/issues/1149) about 2 entry points problem, if you are interested.

**Comment by nktssh** [comment] 2016-12-25 12:49
Find comment about current topic in rollup repo https://github.com/rollup/rollup/issues/126#issuecomment-240038057

**Comment by zech** [comment] 2016-12-25 14:41
@Andarist Yes thank you. I'm following this topic as well.

@nktssh This is indeed a cheap workaround as it will mix up ES6 and ES5 code during build. But at least it works.

Hopefully all these legacy and jsnext workarounds go away soon :-)

**Comment by nktssh** [comment] 2016-12-25 15:29
@zech what do you think, how it can be solved?

Found a thread on npm repo about enhancing "main" field and pass directory there
https://github.com/npm/npm/issues/10506

Resolution:
> This would require changes to the Node module resolution algorithm. As was noted on nodejs/node#3953 when @evanlucas closed it, the Node module loader is basically sacred writ at this point, and won't be changed.

**Comment by Andarist** [comment] 2016-12-27 08:04
The solution of splitting the lib into separate modules and have them required by each other if neccessary - monorepo style - seems the most viable. 

@zech how would it mix up es6 and es5 code during the build? what do you mean?

**Comment by zech** [comment] 2016-12-27 11:06
@Andarist I was referring to the webpack workaround. @nktssh explained it here https://github.com/redux-saga/redux-saga/issues/689#issuecomment-269120552

It looks like seperate packages would be the best solution. In the meanwhile documenting the issue will help.

**Comment by Andarist** [comment] 2016-12-27 12:18
Hm, I've just checked with [validate-npm-package-name](https://www.npmjs.com/package/validate-npm-package-name) and `redux-saga/effects` is not a valid package name, `@redux-saga/effects` would be. So its probably not a problem as it would be a hard dependency of the `redux-saga`.

Do you know if a package can have 2 names?

Also - would you be kind enough and send a PR with a short note about bundling with rollup and suggesting to use this form
```
import { delay, effects } from 'redux-saga'
const { call } = effects // same thing for utils
```
I think its the better way for now, especially when we are discussing here splitting into 2 packages and that would certainly break this `import { call } from 'redux-saga/es/effects'`. 

Do you know though if my proposed approach ruins tree-shaking? Aint sure how it works exactly and how smart it can be, im wondering if [this reexporting](https://github.com/redux-saga/redux-saga/blob/master/src/index.js#L10-L13) of the whole thing can break the benefits of it

**Comment by zech** [comment] 2017-01-02 20:15
> Hm, I've just checked with validate-npm-package-name and redux-saga/effects is not a valid package name, @redux-saga/effects would be. So its probably not a problem as it would be a hard dependency of the redux-saga.

> Do you know if a package can have 2 names?

I think you've got us wrong. We're talking about seperate package names for ES6 and non ES6 code. For example `redux-saga` stays as is with it's legacy ES5 code. Then a second package is created like `redux-saga-jsnext` containing only code written with the latest standard. Or do it the other way around if you want `redux-saga-es5` or `redux-saga-legacy` ;-)

But the package structure remains as is except that there is no `es/` folder anymore.

> Also - would you be kind enough and send a PR with a short note about bundling with rollup and suggesting to use this form

You mean PR for documentation? Can you tell me where you want me to put it? Troubleshooting? But bear with me because i've not done that very often.

> Do you know though if my proposed approach ruins tree-shaking? Aint sure how it works exactly and how smart it can be, im wondering if this reexporting of the whole thing can break the benefits of it

I'm not 100% confident but as I see it this won't break tree-shaking.

**Comment by nktssh** [comment] 2017-01-03 08:34
@zech actually, I with @Andarist get you wrong - my thoughts was about two packages: one is main and one for 'effects'

**Comment by zech** [comment] 2017-01-03 18:48
Then I got the lodash approach wrong. To be honest I did not look into it.

But I don't like the lodash way for redux-saga because the effects are more coupled to redux-saga. lodash on the other side has more distinct modules

**Comment by nktssh** [comment] 2017-01-03 19:04
what about leave only one entry point and desctructure effects from there like an example from @Andarist 
```
import { delay, effects } from 'redux-saga'
const { call } = effects
```
This is another possible solution.

Moreover, some libs (like `redux-form`, for example) just have exported inner Action Creators on the top-level of lib API, near the components and helpers, e.g.
```
import { change, submit, arrayRemoveAll, Field, Form, reduxForm } from 'redux-form'
```

What do you think about this approach?
Do `redux-saga` really need this `effects` separate import?
Besides, as I can see from [v0.14.0 release notes](https://github.com/redux-saga/redux-saga/releases/tag/v0.14.0), a lot of people are confused about two imports

**Comment by zech** [comment] 2017-01-03 19:12
I'm fine with this approach as well. That's what I meant with the 

> BTW. when you already re-export effects within the main module JS.  Why not change the documentation to use it this way in general and leave the effects.js just for historic reasons to not break code for others?

part. Would be the easiest way around i think.

**Comment by nktssh** [comment] 2017-01-03 19:14
@Andarist what do you think about this?

**Comment by Andarist** [comment] 2017-01-04 12:17
> Besides, as I can see from v0.14.0 release notes, a lot of people are confused about two imports

That confusion was only about things like `take` and `takeEvery` being exported from other modules. Not that 2 modules are confusing in general.

> Do redux-saga really need this effects separate import?

Personally I think this distinction helps people understand the idea behind `effects` (plain objects with appropriate structure, just like redux actions are - plain objects with `type` property)

@zech 
> You mean PR for documentation? Can you tell me where you want me to put it? Troubleshooting? But bear with me because I've not done that very often.

Yeah, Troubleshooting seems like a good place for this one.

@issue
still needs to think about the issue and decide what to do, w8ing also for @yelouafi's comment on the matter

**Comment by zech** [comment] 2017-01-09 19:56
Sorry for the delay. I was on holiday till today. I finally made the PR right now.

**Comment by Andarist** [comment] 2017-01-14 23:42
The fix is pending in the PRs here - https://github.com/redux-saga/redux-saga/pull/724 . How much of the problem does it cause now? Does the fix require using a forked repo? If so Im gonna push the simpler fix faster and release updated library asap.

Sorry for the delay and all, Ive kinda messed up things here. 

cc @ok111net

**Comment by zech** [comment] 2017-01-16 12:24
@Andarist Yes it would require a forked repo as i cannot build. But for now i've done a manual change within the file omitting the `CHANNEL_END` export waiting for a new release.

**Comment by Andarist** [comment] 2017-01-16 12:29
Ok, I'll release a faster patch version asap and let you know.

pon., 16 sty 2017 o 13:24 użytkownik Tim Zech <notifications@github.com>
napisał:

**Comment by zech** [comment] 2017-01-16 12:31
Don't rush it. But thank you for your efforts.

**Comment by Andarist** [comment] 2017-01-16 23:44
@zech @ok111net - please check out the new release and let me know

**Comment by zech** [comment] 2017-01-17 09:30
It builds and works. Thank you.

**Comment by nktssh** [comment] 2017-02-19 14:34
@Andarist I think we can close it?

Also, it can be useful for all who tired with destructuring of `effects`: I've created small package called `redux-saga-effects`, just for better development experience. Take a look
https://github.com/nktssh/redux-saga-effects

**Comment by Andarist** [comment] 2017-02-19 23:52
I would like to keep this opened as a reminder that something should be done in the library itself. Possibly we should release 2 builds, but thats the subject for the future for now, as there are more pressings matters at the moment.

About your package - couldnt you spread them? Would it break tree shaking? I havent done it yet, so aint familiar with the rules involved ;)

**Comment by nktssh** [comment] 2017-02-20 10:12
@Andarist 
>  more pressings matters at the moment

sure, np! Just want to check if it still relevant.


> couldnt you spread them? Would it break tree shaking?

it's a first version, will try to move package in dynamic direction.
I also don't like manual re-export - it means that I need to keep eye on the `redux-saga` releases.
Will see how far I can get with dynamic exports - ES6 modules are non-dynamic by design.
What can really solve this problem - extracting `effects` into separate package, all other things are workarounds (it was suggested earlier in this thread and discussed, I know).

**Comment by Andarist** [comment] 2017-04-05 11:35
hey guys, would [this one](https://github.com/rollup/rollup-plugin-alias) solve the issue for you?

**Comment by Andarist** [comment] 2017-04-05 18:50
thanks to @Ephys I'll release a patch version today which should fix this problem entirely and fixes/hacks like:
- aliasing
- @nktssh 's `redux-saga-effects` package
- importing `effects` from `redux-saga`
- etc

should become obsolete :tada:

**Closed by Andarist** 2017-04-05 18:50 UTC
Labels: bug

**Comment by tcrossland** [comment] 2017-05-04 09:02
This also affects the brunch build tool:

https://github.com/brunch/brunch/issues/1695

**Comment by Andarist** [comment] 2017-05-04 09:14
@tcrossland I think this is brunch's issue. Answered there and hopefully we'll manage to find a solution.
