### ISSUE TITLE
Webpack4 issues?

### ISSUE THREAD

**Issue by enrique-ramirez** [redux-saga/redux-saga#1346] opened 2018-02-27 00:10 UTC
Hi!

I'm trying to upgrade to webpack 4 and, after some changes here and there, my bundle compiles and I can see my dev server.

However, the bundle throws an error: `Uncaught TypeError: (0 , _reduxSaga2.default) is not a function`. This happens exactly on the line where I call `createSagaMiddleware()`:

```js
// configureStore.js
import { createStore, applyMiddleware, compose } from 'redux'
import { fromJS } from 'immutable'
import { routerMiddleware } from 'react-router-redux'
import createSagaMiddleware from 'redux-saga'

import rootReducer from 'store/reducer'
import rootSaga from 'store/saga'

const sagaMiddleware = createSagaMiddleware()

const configureStore = (initialState = {}, history) => {
  const middlewares = [
    sagaMiddleware,
    routerMiddleware(history),
  ]

  const composeEnhancers =
    typeof window === 'object' &&
    window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__
      ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__({})
      : compose

  const store = createStore(
    rootReducer,
    fromJS(initialState),
    composeEnhancers(applyMiddleware(...middlewares)),
  )

  sagaMiddleware.run(rootSaga)

  return store
}

export default configureStore

```

After some googling, I stumbled upon https://github.com/redux-saga/redux-saga/issues/898 which seems like a similar issue, also due to webpack, but I'm at a loss here. Any ideas?

Here's my current dependencies:

```json
  "dependencies": {
    "redux": "^3.7.2",
    "redux-saga": "^0.16.0"
  },
  "devDependencies": {
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.9",
    "webpack-dev-server": "^3.0.0",
    "webpack-hot-middleware": "^2.21.0"
}
```

**UPDATE:** Forgot to mention that if I change the `createSagaMiddleware()` to `createSagaMiddleware.default()`, things work fine, however I couldn't call this a workaround since jest fails with `TypeError: _reduxSaga2.default.default is not a function` when this code is executed.

**Comment by Andarist** [comment] 2018-02-27 09:12
I had not time yet to play with webpack@4, could you prepare a slimmed down repro repository so I could check it out?

**Comment by enrique-ramirez** [comment] 2018-02-27 19:17
Hello @Andarist 

I tried to create a slimmed down repo and couldn't reproduce the issue. Here's the repo: https://github.com/enrique-ramirez/redux-saga-demo it works fine, though.

After some tests on my own repo, it seems to be a problem ONLY in development mode, for some reason. Production builds work fine. I've created a slimmed version of my repo (it's still quite heavy, sorry for that) in case you have some time to help me out figure out what's wrong: https://github.com/enrique-ramirez/react-redux-boilerplate

To reproduce the issue, just install dependencies, run `yarn start:dev` and once the bundle completes, open http://localhost:8080

If you open your console, you'll see the error I mention, along with some console logs. If you then open `src/store/configureStore.js` and change the line from `createSagaMiddleware()` to `createSagaMiddleware.default()`. It'll work.

Any help would be greatly appreciated, if only just to point me into the right direction. Sorry for the trouble!

**Comment by Andarist** [comment] 2018-02-27 23:10
Will try to look into this 2morrow, thanks for repro.

**Comment by Andarist** [comment] 2018-02-28 08:37
I've tried right now and it worked. Even after changing this:
```js
const sagaMiddleware = typeof createSagaMiddleware === 'function' ? createSagaMiddleware() : createSagaMiddleware.default()
```
to this
```js
const sagaMiddleware = createSagaMiddleware()
```

I see in your webpack config that you set `mainFields` - is there any reason why u override the default?

**Comment by enrique-ramirez** [comment] 2018-02-28 23:57
Hello @Andarist 

Thank you. Indeed, removing the `mainFields` config (which I can't remember why I set in the first place) works fine. Sorry for the trouble!

**Comment by Andarist** [comment] 2018-03-01 09:39
No problem. Going to close this issue then 😃

**Closed by Andarist** 2018-03-01 09:39 UTC

**Comment by froatsnook** [comment] 2018-08-11 19:15
In case someone else runs across this, I had a similar error until I removed `optimization.concatenateModules: true`.  Which is strange because I have `mode: "development"` and I thought module concatenation was production only.

**Comment by paulwalczewski** [comment] 2018-08-13 10:55
Thanks @froatsnook! I've wasted nearly 5 hours to find the issue wrongly thinking I've either broken my sagas while refactoring or there is something wrong with webpack... and your answer guided me where the issue actually was!

In my case, I had concatenating enabled with plugins
new webpack.optimize.ModuleConcatenationPlugin()

moving that into production-only case solved the issue.

**Comment by MarkLyck** [comment] 2019-11-06 20:29
I'm having this same problem but when switching from webpack to parcel-bundler.

Any ideas how to solve this using parcel?

**Comment by Andarist** [comment] 2019-11-06 23:28
> I'm having this same problem but when switching from webpack to parcel-bundler.

This is barely a description of the problem. Please open a new issue with a runnable repro case and I might take a look at your problem then.

**Comment by MarkLyck** [comment] 2019-11-07 13:15
> This is barely a description of the problem. Please open a new issue with a runnable repro case and I might take a look at your problem then.

I'm not saying this is a problem/bug with redux-saga. It's more likely a bug/problem with parcel or `react-admin` (the node module this error happens in).

I was just adding to the conversation as this was the only ticket that made me realize what the bug I 've spent hours on was actually related to. So if someone goes to search this bug with parcel, this might show up and save them the hours it took me to find this issue.

and if someone else happens to solve this and have an answer that would be great too 😅

But yeah, I don't think this has anything to do with a bug in redux-saga, more likely an incompatibility in parcel-bundler.

**Comment by Andarist** [comment] 2019-11-07 13:25
Sorry if my tone was harsh - I didn't mean it to be. Your reported issue is with parcel so it might look similar to the one reported here, but it is definitely not the same. So it would actually be beneficial if you could reproduce it on its own and share that repro. In such a case I could even try to help you or give more information which could be shared with Parcel so they would know more about the root cause and could more easily fix it.
