### ISSUE TITLE
Yielding on a synchronous function inside a for loop causes the generator to stop running.

### ISSUE THREAD

**Issue by andrewyalung** [redux-saga/redux-saga#2207] opened 2021-07-23 17:24 UTC
### Steps to reproduce
```javascript
function randomFunction() {
  return true;
}

export function* increment() {
  for (let i = 0; i < 5000; i++) {
    console.log("Before", i);
    yield call(randomFunction);
    console.log("After", i);
  }

  yield put({ type: "INCREMENT" });
}
```

Attempt to run `increment` and you'll notice that the for loop stops running around ~1500 iterations and `yield put({ type: "INCREMENT" }); ` is never called.

#### Description of the bug/issue

When calling `increment`, the for loop will freeze and stop running around ~1500 iterations. The for loop does not exit and `yield put({ type "INCREMENT" });` will never be called. Simply changing `randomFunction` to an async function resolves this issue. Also, it doesn't need to be `yield call(randomFunction)`, simply `yield randomFunction()` causes this same issue.

At my company, we frequently use `yield call` on synchronous functions for testing purposes.

#### Example
https://codesandbox.io/s/flamboyant-snowflake-c2x05?file=/src/sagas/index.js

I forked the counter example and manipulated the `incrementAsync` function to reproduce this issue. You'll notice that clicking the `Increment async` function never increments the counter.

### Actual results
The counter is not incremented because the generator function dies in the for loop.

### The Expected results
The counter to increment by 1 after clicking the function.

### Environment information
Redux Saga: 1.1.3

**Comment by tomasztomys** [comment] 2021-07-25 20:36
similar issue in my project

**Comment by Andarist** [comment] 2021-07-26 10:17
This is sort of a duplicate of https://github.com/redux-saga/redux-saga/issues/1592 

I was unable to fix this. The fix would probably require not relying on the native call stack so much, it should be flattened and things should be scheduled manually **without** breaking any existing tests. I could review a PR fixing this - but I'm afraid that I don't have time to dig into this myself.

**Closed** 2022-02-26 02:56 UTC
Labels: bug, duplicate
