### ISSUE TITLE
DOM Testing issue in JEST

### ISSUE THREAD

**Issue by kumar155** [redux-saga/redux-saga#1156] opened 2017-09-04 04:32 UTC
[https://stackoverflow.com/questions/45997768/how-to-test-the-dom-events-using-jest](url)

this is my issue i have posted in stackoverflow somebody help me out this i'm struggling to identify the solution

**Comment by Andarist** [comment] 2017-10-07 19:37
The issue is no longer available on stackoverflow, thus im closing this. If you still have any questions, please just create new issue.

**Closed by Andarist** 2017-10-07 19:37 UTC
