### ISSUE TITLE
Get additional loader errors when trying to build with babel-plugin-redux-saga

### ISSUE THREAD

**Issue by philbarresi** [redux-saga/redux-saga#2012] opened 2020-02-06 06:47 UTC
#### Steps to reproduce

1. Clone https://github.com/philbarresi/demo-babel-plugin-redux-saga-issue
2. `npm install` 
3. `npm run build`

The build will then fail.

#### Description of the bug/issue

Attempting to build while using babel loader and babel-plugin-redux-saga causes the build to fail

```
 {
            test: /\.(js|jsx)$/,
            include: jsSourcePath,
            loader: require.resolve("babel-loader"),
            options: {
              babelrc: false,
              presets: [
                [
                  require.resolve("@babel/preset-env"),
                  {
                    useBuiltIns: "usage",
                    corejs: 3
                  }
                ],
                require.resolve("@babel/preset-react")
              ],
              plugins: ["babel-plugin-redux-saga"],
              compact: true
            }
          },
```

#### Steps to reproduce the bug/issue

1. See above
...

#### Example
I have provided a demo repository at https://github.com/philbarresi/demo-babel-plugin-redux-saga-issue

### Actual results

```
ERROR in ./src/js/sagas/test/index.js 15:131
Module parse failed: Unexpected token (15:131)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|  */ // export all watcher sagas as an array to be composed in the top level
| // root saga
> Object.defineProperty(fetchManifest,"@@redux-saga/LOCATION",{value:{fileName:"src/js/sagas/test/index.js",lineNumber:8,code:null}})export default testSagas;function getManifest(){return Promise.resolve({icons:["$pac","0xbtc","2give","abt","act","zrx"]});}
 @ ./src/js/sagas/index.js 1:1160-1202 1:1417-1426
 @ ./src/js/config/configureStore.js
 @ ./src/js/index.js
 @ multi ./src/js/index.js
```

### The Expected results

I expect the bundle to be built.

### Environment information

Redux saga 1.1.3

```
    "@babel/core": "^7.8.4",
    "@babel/polyfill": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-redux-saga": "^1.1.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "core-js": "^3.6.4",
    "fibers": "^4.0.2",
    "file-loader": "^5.0.2",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-hot-loader": "^4.12.19",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-saga": "^1.1.3",
    "thread-loader": "^2.1.3",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10"

```

**Comment by Andarist** [comment] 2020-02-06 10:49
Interesting. I've located the syntax error and confirmed the issue - but not sure why the output has been generated like this. Need to investigate further, might a bug in Babel itself.

**Comment by philbarresi** [comment] 2020-02-06 18:34
I'm not sure why, but adding an extra semicolon to the template resolves the issue:

```javascript
  var extendExpressionWithLocationTemplate = template(`
    Object.defineProperty(TARGET, SYMBOL_NAME, {
      value: {
        fileName: FILENAME,
        lineNumber: LINE_NUMBER,
        code: SOURCE_CODE,
      },
    });;
  `);
```

**Comment by philbarresi** [comment] 2020-02-06 19:00
Update: that actually makes no sagas run, so that's nice. probably only an accidental fix. Do you have any recommendations where I should post this issue?

**Comment by Andarist** [comment] 2020-02-06 19:18
I think I will be able to fix this on our side - need to wrap the inserted expression with a statement, I'm still looking into why this happens in the first place though.

**Comment by philbarresi** [comment] 2020-03-10 02:58
Were you ever able to figure out why that happened? I looked through the code again and don't really understand.

**Comment by brianneisler** [comment] 2021-03-24 05:58
I think i've sorted out the issue here. After reading this post... 

https://github.com/babel/babel/issues/10526

I realized that the `babel-plugin-redux-saga` was extracting the CallExpression from the ExpressionStatement. 

https://github.com/redux-saga/redux-saga/blob/master/packages/babel-plugin-redux-saga/src/index.js#L53

This is desired in the case of the `FunctionExpression` and the `YieldExpression` but not in the case of the `FunctionDeclaration`. When doing this on the `FunctionDeclaration` it causes the trailing semicolon to be removed and results in errors when the next expression is concatenated to the wrapped one.

**Comment by brianneisler** [comment] 2021-03-24 06:12
I've started a PR here that fixes the issue https://github.com/redux-saga/redux-saga/pull/2171

**Comment by neurosnap** [comment] 2022-12-15 15:26
Greetings!  Since no progress has been made for awhile I'm going to close this issue.  If anyone stumbles upon this issue and wants to help us debug or provide a PR, please feel free to comment and we can reopen.  Thanks!

**Closed by neurosnap** 2022-12-15 15:26 UTC
Labels: bug
