### ISSUE TITLE
TypeScript Cancelled Missing

### ISSUE THREAD

**Issue by JesterXL** [redux-saga/redux-saga#608] opened 2016-10-30 16:13 UTC
Still learning TypeScript casting, but I believe v0.12.1 didn't fix all the missing TypeScript types. I'm using Angular CLI 1.0.0-beta.17 with the `tsconfig.json` set to ES6 output so generators, and thus sagas, work.

<img width="1205" alt="screen shot 2016-10-30 at 12 03 23 pm" src="https://cloud.githubusercontent.com/assets/424737/19837854/8a95c1e4-9e99-11e6-91cf-886bb35dd118.png">

Looking at where error might potentially be, the `effects.d.ts` looks correct, however, and you can see the interface for `CancelledEffect` has a cancelled property, so... confused. @jhsu Do you know what it could potentially be?

**Comment by JesterXL** [comment] 2016-10-30 16:18
Temporary workaround to get it compiling:

```typescript
const myThing:any = rootSaga;
const rootSagaResult = sagaMiddleware.run(myThing);	
```

**Comment by aikoven** [comment] 2016-10-30 16:18
Can you please post the code fragment where it fails?

**Comment by JesterXL** [comment] 2016-10-30 16:19
Yup:

```typescript
export class AppModule
{
	constructor(ngRedux:NgRedux<IAppState>)
	{
		ngRedux.configureStore(rootReducer, {}, [ createLogger(), sagaMiddleware]);
		const myThing:any = rootSaga;
		const rootSagaResult = sagaMiddleware.run(myThing);	
		rootSagaResult.done.catch((err)=>
		{
			console.log("Error in Sagas", err);
		});
	}
}
```
It's mad at the `sagaMiddleware.run`.

**Comment by aikoven** [comment] 2016-10-30 16:26
Seems to be a result of some of `yield`ed value types, although it's not enough to tell where the problem is exactly.
TypeScript is still not very good at generators, but at least it can check types of values you `yield`. My current approach is to set return type of every saga to `SagaIterator`:
```ts
import {SagaIterator} from "redux-saga";

function* someSaga(): SagaIterator {
  // ...
}
```
This way you always know that you only `yield` correct values i. e. effects.

**Comment by JesterXL** [comment] 2016-10-30 16:31
Nice! I'll try that, and once I get her 100% compiling without `any`'s scattered all over the place, I'll update this thread.

**Comment by JesterXL** [comment] 2016-10-30 16:37
Another problem is you can't use Enum's for Actions:

```typescript
enum Actions
{
	PING,
	PING_ERROR,
	PINGED,
	
	LOGIN,
	LOGGED_IN,
	LOGOUT,
	LOGIN_ERROR
}
```

As soon as you attempt to register those with `takeLatest`, it's expecting basically a String. You could use Actions[Actions.PING], but sadly, while that evals to a string, all your switch statements in your reducers are actually numbers at runtime. You CAN set them to string values in TypeScript playground, but that's against the documentation, and it makes it look like it's an error. Generated JavaScript works, though. :: shrugs ::

**Comment by aikoven** [comment] 2017-02-12 07:47
Covered by https://github.com/redux-saga/redux-saga/pull/740.

**Comment by Andarist** [comment] 2017-02-12 11:04
Gonna close it as its included in the PR that will get merged soon.

**Closed by Andarist** 2017-02-12 11:04 UTC
Labels: help wanted, Typings
